### ISSUE TITLE
Large amounts of lag caused by HediffGivers

### ISSUE THREAD

**Issue by RadHazard** [notfood/RimWorld-MoreThanCapable#2]
I have a lategame colony that's experiencing large amounts of lag.  I've been using the Performance Analyzer to track down the culprits, and I think MoreThanCapable is a major one.

A significant amount of pawn ticking time is being spent in my pawns' HealthTick:
![image](https://user-images.githubusercontent.com/6283552/132649944-7fe73164-60d9-4ddf-861b-7e00adf7d8cc.png)

Examining the health tick shows that HediffGivers are overwhelmingly the cause:
![image](https://user-images.githubusercontent.com/6283552/132650194-eab13cf4-9ca5-4147-854c-04f7082994e4.png)

And profiling the different HediffGivers pins the MoreThanCapable HediffGivers as by *far* the most expensive:
![image](https://user-images.githubusercontent.com/6283552/132650418-1e915275-d34a-4ddb-a7d0-496a1fa462bd.png)

Digging deeper, I think there's a simple fix that will buy a huge amount of performance:  
![image](https://user-images.githubusercontent.com/6283552/132650658-238bc42f-af5a-4f40-98ed-ea686c4908ff.png)

If the checks in this method were inverted, the expensive IsBadWork() call would be deferred only if the bad work is active:
https://github.com/notfood/RimWorld-MoreThanCapable/blob/04c41254d075a72450809f0e9063e49aecdb68bb/Source/MoreThanCapableMod.cs#L80-L83

**Comment by notfood** [comment]
Good catch

**Comment by notfood** [comment]
Closed by https://github.com/notfood/RimWorld-MoreThanCapable/commit/187ef462a7e0fc932e1d92db79f8d3fcc328b701

**Comment by RadHazard** [comment]
![image](https://user-images.githubusercontent.com/6283552/132659044-679d8016-d075-4542-9f56-37c1aa0d2622.png)
Looks like that cut the run time of the HediffGivers by two thirds!  They're still pretty expensive, but I did gain something like ~20-40 TPS already so that's a *huge* improvement.

Unfortunately I can't see any easy fix to cut it down further.  All the runtime for IsBadWork is concentrated in the .Contains() call now, but that's probably just an artifact of how IEnumerables work.  The analyzer won't let me examine any deeper, so I don't know what's making it so expensive.
![image](https://user-images.githubusercontent.com/6283552/132657175-ff5b9987-7d98-4975-96b8-624563007226.png)

**Comment by notfood** [comment]
It could use some cache but that opens another can of worms and mod incompatibilities. I'll consider if it's doable.

**Comment by RadHazard** [comment]
You could possibly use a cache that gets refreshed every in-game hour or day or something like that.  I can't think of a mod that has disabled worktypes change that often.

Alternatively, you might be able to just change the LINQ query to be faster.  If the worktag Dictionary used HashSets internally, you could call something like `.Any(set => set.Contains(tag))` instead of flatmapping it into a huge list and running contains on that.

**Comment by notfood** [comment]
I tried to optimize it. Can you test this commit https://github.com/notfood/RimWorld-MoreThanCapable/commit/4aafd2024c94252e78eb9162b6a15e53f631a9ce ?

I'll push it to the workshop once I get an answer from you.

**Comment by RadHazard** [comment]
Unfortunately it doesn't look like the changes made much of a difference :/

![image](https://user-images.githubusercontent.com/6283552/132782625-ec1274ef-f18b-46a3-8519-5206b991f128.png)

On the other hand, I had a showerthought that panned out nicely.  It turns out the tags are already on the def, so there's no reason to query the dictionary at all.  You can change IsBadWork to a constant time check like so:

```
public static bool IsBadWork(Pawn pawn, WorkTypeDef wtd)
{
    return (wtd.workTags & pawn.CombinedDisabledWorkTags) != WorkTags.None;
}
```

I tested it on my local copy and the difference was a full order of magnitude:
![image](https://user-images.githubusercontent.com/6283552/132784819-cc1bdece-5bb3-4e1a-8d3b-f5f678962651.png)

**Comment by notfood** [comment]
Implemented your suggestion. I tested things, seems ok. I'll upload.

https://github.com/notfood/RimWorld-MoreThanCapable/commit/f1d8f051979335200f36e4b81f1ac1b542aef203

**Comment by notfood** [comment]
All seems good
